### ISSUE TITLE
Time to have dynamix enforce icon sizes?

### ISSUE THREAD

**Issue by Squidly271** [limetech/webgui#106]
Dynamix is inconsistent in places where in some spots (plugins tab), the icons are resized to 48px, but other areas (settings tab) there is no forced sizing, and its up to the author of the plugin to resize the settings icon chosen appropriately.  Everywhere in the GUI where icons are expected to be a certain size, the size should be enforced by dynamix and not by the add-on authors.

While the current system does work, a ton of the icons for plugins in CA look terrible because the author is simply reusing the 48px low res icon from the GUI.

**Comment by eschultz** [comment]
Good point.  Besides ensuring the GUI is restricting icons to a certain size throughout, the author should provide a icon that is exactly double the width and height of the largest fixed size in the GUI to make them look nice for HiDPI screens.

Lets say the GUI resizes icons to 48px and CA resizes icons to 96px.  The author should then provide icons at 192px.

**Comment by bergware** [comment]
I added size attributes to the images and let css do the requested sizing. Guess we can close this point.
