### ISSUE TITLE
Dynamix webGui v2017.05.26 -- parent directory icon

### ISSUE THREAD

**Issue by thezoggy** [limetech/webgui#111]
when browsing disk/share, the 'parent directory' blends in with the rest of the folders.. it should have a return icon not a folder icon
![img](http://zoggy.net/firefox_2017-05-30_13-39-14.png)

example of what you normally see:
![img2](https://i.stack.imgur.com/R224e.png)

also the table is not very responsive in design..

**Comment by thezoggy** [comment]
also the last modified is a 'fixed' character size as the data is consistent.. that should go before size which its data is dynamic in how many characters.

**Comment by thezoggy** [comment]
@bergware bump

**Comment by bergware** [comment]
Several enhancements are done for the upcoming version.
