### ISSUE TITLE
Docker Client/Updater adds :latest even if another tag exists

### ISSUE THREAD

**Issue by Speeder2000** [limetech/webgui#112]
Referencing this post -
https://forums.lime-technology.com/topic/55298-is-it-possible-to-stop-the-latest-tag/

In a scenario where there's already a docker tag present that is not "latest", docker updater appends :latest, for example "Pulling image: sumologic/collector:latest-syslog:latest"
latest-syslog is the tag, but :latest is still added. If :latest tag exists, it is not added again.

**Comment by bergware** [comment]
Made a correction to fix this.
