### ISSUE TITLE
need unRAID icon in dynamix.vm.manager

### ISSUE THREAD

**Issue by ljm42** [limetech/webgui#124]
Minor request... Would you please add an unRAID icon to the webgui/plugins/dynamix.vm.manager/templates/images/ folder? This will allow us to assign an appropriate icon to an unRAID VM.  Thanks!

**Comment by realies** [comment]
@ljm42, virtualising unRAID seems to be frowned upon.

**Comment by ljm42** [comment]
Thanks!  I've updated the [How to install an unRAID VM on an unRAID host](https://forums.lime-technology.com/topic/60106-guide-how-to-install-an-unraid-vm-on-an-unraid-host/) guide to use this image
