### ISSUE TITLE
Docker update status not working for ghcr.io

### ISSUE THREAD

**Issue by djerfy** [limetech/webgui#1245]
Hi,

I found a problem with containers from ghcr.io (Github), the update status doesn't work correctly.
An example in `/var/lib/docker/unraid-update-status.json` file:

```json
{
    "djerfy/telegraf:latest": {
        "local": "sha256:fb1159480b39372b835683cd0ac8fcb4abc67e00e7566534bb550d2dce2ef0bc",
        "remote": "sha256:97d05b8e4bc95f9db4365964a1fed7c1d00316f13d888af04e192db53fac477d",
        "status": "false"
    },
    "quay.io/keycloak/keycloak:latest": {
        "local": "sha256:b8f2a453a17a244a829fdafdb08dd77f719d3622bc3987c76a81771c0913b882",
        "remote": "sha256:b8f2a453a17a244a829fdafdb08dd77f719d3622bc3987c76a81771c0913b882",
        "status": "true"
    },
    "ghcr.io/tarampampam/error-pages:latest": {
        "local": "sha256:47549faeaa41b225312b1bebb3e593f1a29ed02fcdbe175a4eb1e20ec7bd5e9b",
        "remote": null,
        "status": "undef"
    }
}
```

* `djerfy/telegraf:latest` (docker.io by default, public) -> update ready
* `quay.io/keycloak/keycloak:latest` (quay.io, public) -> up-to-date
* `ghcr.io/tarampampam/error-pages:latest` (ghcr.io, public) -> not available

I don't known why I've `undef` status in this file.

**Comment by djerfy** [comment]
After a quick debug, ghcr.io use OCI model. Already done but available in the next release of Unraid.
* Issue: https://github.com/limetech/webgui/issues/1111
* Commit: https://github.com/limetech/webgui/commit/cd687b329467d553b7ea3db7ad63585a3e0f216f

**Comment by ljm42** [comment]
Hi, let me encourage you to report issues in our friendly community forums, as more folks are around to help guide you to solutions. Here is a recent thread about this issue, which mentions a plugin that will fix this problem in the current version of Unraid:
  https://forums.unraid.net/topic/134016-fix-to-a-small-issue-with-updating-oci-docker-images/

Would you mind closing this issue if you got what you need? Thanks!

**Comment by djerfy** [comment]
Of course, yes I close this issue
