### ISSUE TITLE
Array status icon on rc16b

### ISSUE THREAD

**Issue by realies** [limetech/webgui#228]
<img width="106" alt="screen shot 2017-12-17 at 02 59 02" src="https://user-images.githubusercontent.com/5107843/34076201-4f18fa6e-e2d6-11e7-8b43-a063487cc46a.png">

It is inappropriate to have a battery icon indicating disk array status since there is UPS functionality in unRAID that involves a battery and both are irrelevant to each other. Please use something else that signifies hard disks or a [disk array](http://fontawesome.io/icon/database/).

**Comment by bergware** [comment]
Changed it to less confusing icons.
