### ISSUE TITLE
Grave accent in variables breaks Docker management

### ISSUE THREAD

**Issue by realies** [limetech/webgui#245]
Using the grave accent (`) character in variable field for containers breaks command execution.

Researching what characters are to be escaped and how exec statements should be filtered might be the way forward for exec statements containing user input.

**Comment by eschultz** [comment]
Thanks for the report. I'll be submitting a correction for this and improving the overall arg escaping for Docker in a bit.

**Comment by eschultz** [comment]
Fixed in https://github.com/limetech/webgui/commit/06152c092a8894d4767a82ac09368e6b088179a7
