### ISSUE TITLE
Fetch container status via json pulls instead of page refresh

### ISSUE THREAD

**Issue by realies** [limetech/webgui#247]
When starting/stopping multiple containers it is not practical to have the delay that the page reload causes. Sometimes a container starts after the page has been reloaded, which requires another reload to see the expected status. Please inform the front-end of the containers' status via periodic json updates instead of reloading the page.

**Comment by bergware** [comment]
unRAID 6.5 has inline updates for containers and VMs without the need to completely reload the page when starting or stopping a container or VM.
