### ISSUE TITLE
Tag webgui with OS releases

### ISSUE THREAD

**Issue by realies** [limetech/webgui#289]
Would be great if new unRAID releases are tagged within the `webgui` repository.

**Comment by limetech** [comment]
Yeah used to do that, but good idea to resume this practice.

**Comment by realies** [comment]
Great. If breaking changes are documented somehow, that could allow for defining a compatibility window for upgrading or downgrading `webgui` as a package. What is the position on this?

**Comment by realies** [comment]
@limetech ^
