### ISSUE TITLE
Heads up: we're going to merge 6.4-wip back into master

### ISSUE THREAD

**Issue by limetech** [limetech/webgui#293]
Since development workflow has changed we are going merge 6.4-wip branch back into master and then delete the 6.2, 6.3, and 6.4-wip branches.  The two PR's sitting there for 6.4-wip are going to be lost, but:

"Add VM template for unRAID" is on our road map and noted for a future release, and
"Array status statistics panel space optimisation" is something we won't merge in current form anyway.

We plan to do this on Tuesday **13** March 2018.

**Comment by bergware** [comment]
Your calendar different from mine? Here in Europe Tuesday is 13th. :)

**Comment by limetech** [comment]
We just switched to "Daylight Savings Time" which means we lost a whole day right?

**Comment by bergware** [comment]
With DST we gain one hour, and you guys loose a day. It's a strange world!

**Comment by limetech** [comment]
'merica!
