### ISSUE TITLE
duplicate nav-item id's

### ISSUE THREAD

**Issue by ljm42** [limetech/webgui#373]
The HTML of the menu looks like this:

```
<div id="menu">
  <div id="nav-left">
    <div id="nav-item">..</div>
    <div id="nav-item">..</div>
    <div id="nav-item">..</div>
  </div>
</div>
```

HTML id's are supposed to be unique, wouldn't the nav-item's be better as classes rather than ids?

**Comment by bergware** [comment]
Repeated IDs are allowed too. I don't see anything not working (or incorrectly working) with these assignments.

**Comment by OmgImAlexis** [comment]
Duplicate: https://github.com/limetech/webgui/issues/546

**Comment by OmgImAlexis** [comment]
@bergware hate to be that person but any chance on an update on this? Would really like to get the current accessibility issues fixed up. You can find the others [here](https://github.com/limetech/webgui/issues?q=is%3Aopen+is%3Aissue+WCAG+).
