### ISSUE TITLE
robots.txt

### ISSUE THREAD

**Issue by ljm42** [limetech/webgui#377]
To keep Unraid servers from being indexed by search engines, please consider adding a robots.txt in /usr/local/emhttp that contains:

```
User-agent: *
Disallow: /
```

and then adding this to rc.nginx to serve the file without requiring authentication:

```
#
# robots.txt available without authentication
#
location = /robots.txt {
    auth_basic off;
    allow all;
}
```

**Comment by eschultz** [comment]
We added that block to rc.nginx and @bergware added robots.txt. Thanks guys!

**Comment by ljm42** [comment]
great! this should keep the well-behaved robots away without giving away any details to the bad bots.
