### ISSUE TITLE
Adblocker hides share list table body

### ISSUE THREAD

**Issue by realies** [limetech/webgui#391]
Just noticed that Adblock Plus hides the `#share_list` `tbody` from the `ShareList.page` when the `Block social media icons tracking` option is enabled. It seems that the particular option enforces a stylesheet rule to hide specific element names, and it turns out `#share_list` is within them.

<img width="942" alt="screenshot 2018-09-27 at 20 45 33" src="https://user-images.githubusercontent.com/5107843/46164319-5d3d9500-c296-11e8-8329-d1772150a043.png">

Disabling the option or whitelisting the server address resolves the missing shares in the web interface.

<img width="972" alt="screenshot 2018-09-27 at 20 42 07" src="https://user-images.githubusercontent.com/5107843/46164361-734b5580-c296-11e8-89ad-295eda6c2baf.png">

**Comment by limetech** [comment]
Are you saying this is merely because the element name is "share_list" and if we changed it to something else such as "shareslist" would solve the issue?

**Comment by realies** [comment]
Correct. Not sure how good of an idea is to go down the rabbit hole of satisfying each and every adblocker plugin but thought it might be worth reporting.

At the time of writing, this is the injected stylesheet that the browser extension enforces:

>.fb_content_loader, .floating-share, .followscreen, .footerSocials, .genericon-stumbleupon, .guides16-social-top, .horizontal-share-menu, .icon-connect, .icon-telegram, .in-page-share, .js-share-count, .linfoShare, .main-sub-social, .mod-social-bar, .newSocialShareButtons, .pbtsharethisbutt, .postDelicious, .right_social_mg, .share-article-social, .share-links--link, .shareBtn, .share_email_article, .sharepost, .show_facebook_widget, .siteFooter_socialCon, .social-bar-bottom, .social-h, .social-sharing-v2, .socialIconsRect, .social_btn, .socialb, .socnav, .stm-socials__icon, .th-sharecounts, .twitter_share_count, .vf-share-options, .widget_follow_button_widget, .x-tmblr, a[href^="http://del.icio.us/post"], img[alt="Visit our Facebook page"], #advanced-twitter-widget, #box-gplus, #donate-social, #fb-social-top-buttonOFF, #followbb, #header_google, #lst-instagram, #peek-share, #share-icon, #sitewide-social, #social-promo-flyin, #socialSharingDiv, #socialgroups-info-vk, #topui_container_TopPlayeropen_redes, #yahooBuzzBadge-form, .ShareToolBarTop, .addthis-single-wrap, .article-head__share, .asicon-twitter, .bio-socials, .bt_tweet, .c-home-share-box, .connect-button-twitter, .dh-social-icons-panel, .et_social_fadein, .facebookShareAlert, .fbPageAlert, .flatSocial, .follow_icons_container, .footer-tw, .gallery__share, .gtm-social-link, .hnav-social-list, .icon--instagram, .icon-social-linkedin-green, .image_icon_facebook, .js-gig-social-bar, .like_buttons, .mT-socialLinks, .mnu-ico-fb, .nc_socialPanel, .panel-social-googleplus, .post-share-widget, .review-social-icons2, .sh_facebook, .share-item--google, .shareActions, .share_button, .sharelinkedin, .sharing_nw, .site-nav-social-google-plus, .social--vertical, .social-foot, .social-media-buttons-single, .social-share__button, .socialFollow, .social_tw, .socicn, .sticky-shares-wrap, .td_block_social_counter, .tt-social-media-footer, .twitter_feed, .vc_social_general_icons, .widget_connect_facebook, .wx-fb-activity, a[classes="share_widget"], a[title="Seguici su Google+"], #about-edition-social, #blog-share-widget, #divShareURL, #fb-friction-less, #followUsRight, #header-social, #linkShare, #overftrboxsocial, #share-button-templatoid, #share_data, #sidesocial, #social-network, #socialOverlay, #socialbtn_twitter, #top-social-share-buttons-container, #widget-social, .ShareIt, .actions_twitter, .art_shr_top, .article_pinterest, .besocial, .bq_shareDiv, .c-NavSocial-item, .community__social-desc, .det-media-tw-btn, .essb-flyin, .facebookGroup, .fb-tweet, .fixed-share-btns, .followTwitter, .footer-social-pinterest, .g_share, .gridlove-share, .hf--linkedin, .icomoon-facebook, .icon-share-alt, .icos-social, .jeg_socialcounter, .like-button-google, .m-sharing, .mini-social-icons, .navbar-fixed-bottom__share-icons, .pane-menu-footer-social-menu, .post-meta__option--gplus, .redit_button, .service-links-scmp-weibo-widget, .share-icons-bottom, .share-whatsapp, .share_area_item, .sharegrid, .sharingOptions, .site-footer-social-menu__item, .social--facebook, .social-feed-twitter, .social-list-container, .social-share-links, .socialChannels, .social__follow, .social_sharing, .socialshares, .st_twitter_custom, .tbt_social, .track-action-Twitter, .twitterShareTrigger, .utility-stumble-upon, .widget-twitter-timeline, .wrapper-fixed-social-buttons, [title^="Share on Tumblr"], a[title="Condividi su whatsapp"], #StickySocialContainer, #block-sharethis-sharethis-block, #dcssb-stumble, #facebookpopup-fan-exit, #follow-us-widget, #gtm-header-instagram, #likeThisPost, #news-detail-social-top, #share-ad-dropdown, #share_art, #sidebar-facebook-activity, #social-media-header, #socialMediaMenu, #social_youtube, #theroot-social-panel, #w2bSocialPlaceholder, .PremiumObitShare, .abicon-twitter, .arq-lite-facebook, .article__share-title, .bd-FooterFollow-Icon--linkedin, .box-social, .button_list_menu_social, .comedy_share_title, .dc-social-slick, .entry-social-buttons, .facebook-twitter-share, .fb-promo, .fig-micronav__item--twitter, .follow-widget-instagram, .footer-social-buttons, .fv_sharing, .gplus-link, .headerfacebookicon, .ico-youtube, .icon-pinterest3, .icons-instagram, .j-gplus, .lf-share-item-wrapper, .m-icon-tw, .metro-social, .nav-social-right, .page-social, .poll-share-box, .red-fb, .search-social-icons, .share-googleplus-icon, .share-tools-curated, .share__call-to-action, .sharing-twt, .singlepage-socialicons, .socblock, .social-deferred, .social-link-twitter, .social-share-btns, .socialBar-single, .socialVisible, .social_share_box, .socials-widget, .st_facebook_large, .szoSocialMediaShare, .topmenu_twitter, .twitterCountDiv, .us_share_text, .widget-facebook, .wp_social_single_share_wrapper, [title="Share to Facebook"]:not(.wpel-icon-right), a[onclick^="popUp=window.open('http://pinterest.com/pin/create/button/"], iframe[src^="http://www.facebook.com/plugins/activity.php?"], #SocialBooksTop, #block-footersocialmedia, #ctl00_cphMainContent_ContentBloc_ctl00_pnlSocialShare, #facebook_promo, #follow-icons, #google_plus_right, #leftShare, #nav_social_links, #scrollingSocial, #shareThis, #sharingLinks, #social-links-facebook, #socialLinks, #social_sidebar, #svgFacebook, #videoShareToEmbed, .NavSocial-facebook, .a2a_floating_style, .aol-share, .articleSocialNetwork, .badge-gplus-share, .button-network_facebook, .cnnShareRow, .custombtnsociaux, .email-share-link, .facebook-section, .fb-like-box-outer, .fi-social-channels--svg, .follow-us-google, .footer-section-social, .ft-youtube, .googlepluscommon, .header__social-icons, .ico-facebook-1, .icon-meneame, .icon_youtube, .itemFacebook, .lbShareFacebook, .m-btn-twitter, .menuTwitter, .nav-follow-us, .overlay_facebook, .place-share, .r1-share, .scriptlesssocialsharing, .share-this-new, .sharebar-top-desktop, .sharing-google-plus, .single-post-socials, .socNetworks-footer-article, .social-connect-widget, .social-likes__widget, .social-root, .social-width30, .socialSquare, .social_networking_container, .socialnonsense-wide-articles, .sshare-twitter, .sumome-share-client-wrapper, .top_share, .twitter-tweet-button-single, .uninav-icon-yt, .wdb-social, .wk-twitter, [title="CONNECT WITH US ON FACEBOOK"], a[href^="https://www.meneame.net/submit?url="], div[data-nn-init="sociallinks"], .h-fixed-footer, #ShareButton, #blksocial, #content-social-2, #facebook_facepile, #floating-share-box-wrapper, #gigya-share_gig_containerParent, #js-item-social-slider, #multix_icons_facebook, #rs_youtube, #sharetools-masthead, #social-icon-menu-container, #socialFeet, #social_networking_block, #storyShareContainer, #twittertweetsearch, .Logo-facebook, .Widget-social, .amp-o-social-bar, .articleFooterSocial, .b-ss-share, .blox-social-tools-horizontal, .bts_social, .circle-share, .custom-follow-button, .eins-facebook, .facebook-like-large, .fb-custom-share-mobile, .fe-share, .follow-sharer-icon, .footer-icon-instagram, .fs-twitter, .google_btn, .header-socials, .icn-tumblr, .icon-instagram-icon, .icon_delicious, .it-share, .labelsocial, .lr-social-box, .menu-sliding-social-container, .myyahooHeadButton, .onp-sociallocker-overlap-box, .pwebfblikebox, .sb_share, .share-controls, .share-social-links, .shareSideBar, .share_widgets, .sharify-btn-pocket, .sidebartwitter, .soc-pint, .social-buttons-v2, .social-inner, .social-utilities, .socialPostBottomBar, .social_media, .socialmedia_article_linkbox, .ss-whatsapp, .subscribe-option-twitter, .top-social-share, .twitter-post-share, .uk-icon-twitter-square, .w-sharing-count, .widget_vb_search_social_tips, [data-pin-href^="https://www.pinterest.com/pin/create/"], div[class^="FooterSocialLinks"], img[title="Share at Google+"], #IGsocialslide, #badge_twitter, #coma_social_share, #facebookLikeContainer, #fdbk_tab, #fsb-social-bar, #index-social, #mobile-social, #rightSocialLinkedin, #shareContent, #shareplus_sticker, #social-fixed-links, #socialBookmarkLinks, #social_links, #st-social, #twitter_panel, .HeaderGrid-socialList, .SynFacebookLike, .af-social-btn-big, .article-social-opts, .b-shares, .blog-post-share, .btnSocialStumbleUpon, .cb-widget-social-media, .cs-social-icon, .easy-share, .facebook-flyout, .fastsocialshare_container, .fbook-share, .follow-instagram, .footer-fb-btn, .fourSq-widget, .google-plus-new, .header-social-area, .ic_socials, .icon-gplus-circled, .iconFb, .ion-social-viadeo, .keystone-social-author, .lnkFacebook, .mejs-share, .mtphr-social-widget-links, .nypr-social-icons, .pinitShare, .pst-share, .s24-art-share, .share-buttons-area, .share-section-pink, .shareModule, .share_toi, .sharetools-overlay, .sidebar-social-buttons, .soc-block, .social-button-row, .social-icons-links, .social-onscroll, .social-tools-home, .socialNav, .social_island, .socialize-icon--linkedin, .sprite_youtube, .su-social-media-container, .toolsShare, .twitter-google-follow-box, .ui-social-fixed, .vod_program_social, .widget_synved_social_share, as24-share-menu, a[href^="http://www.twitter.com/share?"], a[title^="follow us on Facebok"], img[alt^="Share this to Yahoo"], #FaceBookTab, #as_facebook_recommend, #ck_sharethis, #facebook-twitter-page-top, #fblikebot123, #footerSocialNet, #icon_linkedin, #menu-socialnbt, #reddit_social_sidebar, #sharecopy, #social-column, #social-wrap, #social_fixed, #socialtabs_gp, #twitterFollowBadge, .FeatureSocial, .SocialShare, .addthis_total_count, .article-soc, .b-footer_social, .block-socialsharingblock, .btn-social-media, .canvas-share-buttons, .cosmo-social, .e-icon-pinterest, .facebook-big-share, .facebookicon, .fbbox-wrapper, .follow-button-gplus, .footer--contact-social, .footer_socialblock, .global-share, .header-interna-share, .i-vertical-share-links, .icon-g-plus, .icon-webplayer_ico_sharing2, .instagram-link, .jssocials-share, .list-item-facebook, .mbdev-custom-social-links, .moretweetsmsg, .node-share-buttons, .picto_googleplus, .prl-header-social, .rui-social, .share-box-wrapper, .share-plusone, .shareIcons, .share_row, .sharethis, .side_share_parent, .smshare, .social-box-float, .social-icon2, .social-network-sharing, .social-surface-rr, .socialMediaIconlg, .social_googleplus, .socialfollowercounter, .sprite-social-facebook, .stt-share, .tm-social-pinterest, .twitter-button-link, .tx-timtabsociable-pi1, .vjs-share-button, .widget_social_follow, .ytp-share-button, a[href^="http://www.facebook.com/dialog/feed?"], a[title^="Join us on LinkedIn"], img[alt^="Follow us on YouTube"], #article-social-wrap, #button_fbook, #facebook-like-box, #fb_linkedIn_page_header, #footer-twitter, #ico-facebook, #menu-reseaux-sociaux, #postShareSnsWrapper, #share-tools-title, #sharebarBottom, #social-bottom, #social-tools-panel_gig_containerParent, #social_bottom_float, #socialreader_content, #twitter-link, .ClickFacebookLike, .SocialLinks, .addthis_button_whatsapp, .article-share-slide, .av-share-box, .block-idg_twitter, .btn-more-share, .c5-social-sidebar, .content-share-block, .dpsp-networks-btns-sidebar, .fa-google-plus-square, .facebook_new, .fb_plug, .flybox-share, .foot-info__socials, .footer__socialIcon, .gig-share-bar-container, .head-social-links, .ht_socials_widget, .icon-facebook-sticky, .icon-twitter-circled, .inline-share-tools, .js-social-toolbar, .linkedin-btn, .mashicon-twitter, .module-story-social, .newsItemSharer, .pg-share-icon-facebook, .post_share_stumble, .rrss__button--email, .share-bar__list, .share-newsvine, .shareDiv, .share_line, .shares--floating, .si-button-pocket, .slideshow__header-share, .social-block-news-page, .social-icon-bar, .social-menu, .social-statistics-widget, .social_di, .sp_twitter, .story-social-share, .tipsy-social-icon-container, .tweetmeme, .twitterpage, .video_actions_sharebutton, .widget_omg_widgets_social_widget, .youTubeBtn, a[href^="http://technorati.com/faves/?add="], a[title^="Follow me on Facebook"], #article-headline-social-list, #btnFB, #extra-share, #fbSlider, #footer-share, #homeTwitterWrapper, #masthead-socialblock2, #popShare2, #share-pinterest, #share_top, #soc_tw, #social-sharing-widget-mobi-sticky, #socialWidgetsWrap, #socialmedia_tools, .Article-FB-Left, .SocialAccordion, .addthis_button_facebook_like, .at-share-v, .blip-follow-us, .c-social, .connect_with_us, .div_share, .exp-video-player__topbar__share, .fb_content_share, .floating-share-bar, .followtw, .footerYouTube, .genericon-tablet, .h-c-social, .horizontal-social-links, .icon-delicious, .icon-tumblr, .in-post-social, .js-share-email, .link-fb, .mainFooterBottomFacebook, .mod-social-bar-item, .new_facebook_16, .pcf-social-media-wrapper, .postDigg, .right_socials_wrap, .share-article-tools, .share-links-footer, .shareBtnContainer, .share_entry, .sharepostwide, .siteFooter_socialHeader, .social-bar-button-share, .social-head, .social-media-module, .social-sharing-vertical, .socialIconsWrapper, .social_btn_single, .socialb_tg, .socnet_left_float, .storifycon-share, .the-social-links, .twitter_sm, .vgtrk-bar-social-wrap, .widget_follow_cb_sidebar_widget, .xplayer-share-control, a[title="linkedin"], img[alt="Visit our Google+ page"], #box-recommendations-fb, #drop-btn-share, #fb-timeline-btn, #followbigbutton, #header_social, #lst-twitter, #persistent-share, #share-icons, #share_list, #slatest_twitter, #social-rail, #socialSharingToolsBox, #socialhdr, #total_shares_horizontal, #yan-share, .ShareTools, .addthis-smartlayers, .article-header-sharing, .aside-news-box-share, .bio-with-share, .bt_twitter, .c-icon--whatsapp, .connect-icon-container, .dialog-social, .et_social_flyin, .facebookShareIcon, .fbRecommend, .flaticon-facebook, .follow_links, .footer-tw-icon, .gallery__share-buttons, .gtmStickyShare, .ho-co-social, .icon--linkedin, .icon-social-mail-circle, .image_icon_facebook_lef, .js-home-social, .like_share.left, .m_follow_us, .mnu-ico-tw, .nda-image-share__wrapper, .panel-social-twitter, .post-sharebox, .review_sharebar_vertical, .share--aside, .share-items, .shareAfterAuthors, .share_button_container, .sharelinks, .sharing_social_count, .site-nav-social-item, .social-1303, .social-media-call-to-action, .social-share__listitem--facebook, .socialFooter, .social_bar_sites, .social_twit, .socicon, .sticky-side-share, .td_social_counter, .tumblr-footer-share, .twitter_follow, .vc_social_icons, .widget_connect_instagram, .wx-local-tweets-hdr, a[data-share="popup"], a[title="Seguici su Twitter"], img[alt="Social Buttons"], #act_share_global_par, #blog-social, #divSocial, #fb-friends, #follow_bar, #header-social-apps-v2, #link_facebook, #overlay-facebook, #share-buttons, #share_div, #siga-facebook, #social-networking-icons-round, #socialOverlayRemix, #socialbtns, #top-socials-follow, #widget-twitter, .ShareLinks, .actnbr-has-follow, .artcl-social-media, .bg-button-twitter, .br-fblike, .c-article-header__social, .community__social-ico, .detShare, .essb-mobile-sharepoint, .facebookHomepageBottom, .fb-twitter, .fixed-sharebar, .followUs, .footer-social-row, .ga-linkedin, .gridlove-share-wrapper, .hf--twitter, .icomoon-facebook2, .icon-share-facebook, .id-AdditionalHeaderContent-el--socialMedia, .jetpack-social-navigation, .like-button-twitter, .m-sharing-toolbar, .mini-social-media-sharing, .navbar-fixed-bottom__share-label, .pane-menu-menu-site-social-widget, .post-meta__option--twitter, .redwaves_social_icons, .service-links-twitter-widget, .share-icons-box, .share_arti_srevamp, .shareicon, .sharingPanel, .site-footer-social-wrapper, .social--fb, .social-feeds-v1-content, .social-list-icon, .social-share-list, .socialCnt, .social__icon, .social_sharing_module, .socialsharetop, .st_twitter_hcount, .tcArticleSocialShare, .tracking_article_social, .twitterSocialIcon, .utils_social_tracking, .widgetFB, [title^="Share on Twitter"], a[title="Condividi"], img[alt="Facebook_32"], #ToolsShareStory, #block-sharing-links, #dcssb-twitter, #facebookpopup-fanback, #follow-widget, #gz-facebook-page-share, #likeThisPostProminent, #news-social-share, #share-ad-inner, #share_bar, #sidebar-fb-social-reader, #social-media-hub, #socialMediaNav, #social_yt, #thread-header-social, #w_twitter_wrapper, .QUISocialList, .abicon-youtube2, .arq-lite-instagram, .article__shares, .bd-FooterFollow-Icon--pinterest, .box-social-buttons, .button_pinterest, .comment-sharing-share, .dc-social-slick-content, .entry-social-connect, .facebook-twitter-wrap, .fb-recommend, .film-share, .follow-widget-twitter, .footer-social-connect, .fv_sharing_classic, .gplus-share, .headersocial, .icoFacebookBig, .icon-pinterest_master, .icons-linkedin, .j-header-follow-us, .lf-social-bookmarks, .m-icon-youtube, .mf-single-article-share, .nav-socials__link, .page-social-counters, .poll-social-header, .red-linkedin, .secArtShare, .share-gp, .share-tools-footer, .share__comments, .sharebuttonu, .sharing-vertical, .singlepost_share, .socbtn, .social-displayer, .social-linkedin, .social-share-button, .socialBarForum, .socialWidget, .social_share_box_wrapper, .socials-wrap, .st_facebook_vcount, .t-article-share-btn-1, .topmenu_youtube, .twitterFeed, .us_twitter, .widget-facebook-2, .wpa-social-icons, [title="Submit to Digg"], a[onclick^="popUp=window.open('http://www.tumblr.com/share/"], iframe[src^="http://www.facebook.com/plugins/likebox.php?"], #SocialContainer, #block-menu-menu-connect-with-us, #ctl00_ctl00_ConMainBody_ConMainBody_Share1_socialSharing, #facebook_reader_wrapper, #follow-links, #google_share, #leftShareTools, #navbar-social, #sdac_footer_facebook_widget-3, #shareThisDisplay, #sharing_bar, #social-links-foot, #socialLinksContainer, #social_sidebar_container, #svgGoogle, .NavSocial-instagram, .a2a_vertical_style, .aol-share-container, .articleToolbarShare, .badge-pinterest-share, .bottom-social-buttons, .button-network_twitter, .cnn_widget_cnn_multi_twitter_widget, .customfollow-us, .email-sharetool, .fb-like-box-wrapper, .fi-social-facebook, .follow-us-icons, .footer-section__social-links, .ftTwit, .googleplustop, .header__social-list, .ico-facebook-circle, .icon-mixcloud, .icona-social, .itemShareBtns, .left-panel-social-icon, .m-btn-youtube, .menu__link--facebook, .nav-footer-social, .ow-social-icons, .player-share-toggle, .ra-share, .scroll-nav-social-item, .share-feed, .share-this-page, .shareToolsItemEmail, .sharebarWrapper, .sharing-info, .single-share, .socRight, .social-contain, .social-likes_ready, .social-row, .socialSticky, .social_networks, .socialplugin, .sshare_buttons, .superads-social-icons, .top_share_link, .twitter-w, .unspoken-getconnected, .wdgt_sharelink, .wl-ico-facebook, [title="Click to share this post on Twitter"], a[href^="https://www.pinterest.com/pin/create/button/"], div[id^="WP_TweetShare_"], #ShareEntryPoint, #bloc-follow, #content-socialshare, #facebook_fanpage, #floating-sharebar, #gigya-sharebar, #js-share, #mvp-foot-soc, #rshare, #shareOptionMore, #sharetoolscontainer, #social-icons, #socialFloatVert, #social_networks-2, #story_share_after, #twitterwrapper, .Logo-google-plus, .WidgetFramework_WidgetRenderer_ShareThisPage, .amp-social-container, .articleFooterSocialSharing, .blvs-share-button, .btsocialfooter, .circle-twitter-share, .custom-google-plus-button, .eins-twitter, .facebook-like-message-holder, .fb-desktop, .feature-photos-share-tool, .follow-site, .footer-icon-pinterest, .fs-vimeo, .google_net, .header-special-social, .icn-twit, .icon-instagram-white, .icon_digg, .it-social-tabs, .lafo-social, .ls-social-links, .menu-social, .n-facebook, .ont-social-networks, .pinterestButton, .pxFacebook, .sbm-follow-fb, .share-controls__container, .share-socials, .shareSocial, .share_with_friends, .sharify-btn-reddit, .sidefacebook, .soc-pinterest, .social-buttons-vertical, .social-insta, .social-post-share, .social-utility, .socialRight, .social_media_block, .socialmedia_float, .ss_sharebar, .top-socialbar, .twitter-promo, .uk-icon-xing, .w-sharing-icon, .widget_vw_widget_social_counter, [data-pin-log^="button_pinit"], a[href^="https://twitter.com/intent/retweet?tweet_id"], div[class^="ShareButtons_"], img[title="Share at LinkedIn"], #IconSocialMediaContainer, #badges-share-block, #communityshare, #facebookPopUpLikeBox, #feeds-facebook, #ftSocial, #industryTweet, #mobileShare, #rightSocialTwitter, #shareCustomLogo, #sharepost, #social-float, #socialBookmarks, #social_linksnewspaper, #stDigg, #twitter_promo, .Header__Button--Social, .SynTwitterShare, .af-social-btns, .article-social-overlay, .blog-post-share-aside, .cb_share_block, .csbwfs-social-widget, .easy-social-profile-buttons-class, .facebook-follow, .favicon-facebook, .fbook_like, .follow-iphone, .footer-fb-icon, .fpbiz_share, .google-plus-share, .header-social-btn {
    display: none !important;
}

**Comment by eschultz** [comment]
Thanks @realies, should be fixed in commit 05f5b2b
