### ISSUE TITLE
Update to Latest Font Awesome and update Icons?

### ISSUE THREAD

**Issue by Dazog** [limetech/webgui#398]
It appears the Gui is using a very old version of Font Awesome.

They have a ton of FREE icons that would better suit the new GUI redesign.

Example:

https://fontawesome.com/icons/apple?style=brands
https://fontawesome.com/icons/linux?style=brands
https://fontawesome.com/icons/windows?style=brands

Etc...

To replace the older windows xp looking ones :)

**Comment by bergware** [comment]
Unfortunately version 5 of font-awesome only offers "solid" icons for free, unlike version 4 which offers both solid and regular icons for free, which in my opinion makes v5 less versatile.

Unraid 6.7 will see new icons designed specically for Unraid. Wait and see.
