### ISSUE TITLE
6.6.6 -- sum.png missing

### ISSUE THREAD

**Issue by thezoggy** [limetech/webgui#438]
webGui/images/sum.png is not found
![unraid](http://zoggy.net/firefox_2019-01-15_19-06-38.png)

**Comment by Squidly271** [comment]
https://forums.unraid.net/bug-reports/stable-releases/666-brokenmissing-image-on-main-tab-r342/?tab=comments#comment-2575

Bonienl already fixed

**Comment by thezoggy** [comment]
ty
