### ISSUE TITLE
Docker update notifications given when not enabled

### ISSUE THREAD

**Issue by Squidly271** [limetech/webgui#481]
@bergware , as per https://forums.unraid.net/bug-reports/prereleases/670-rc5-stop-update-notices-dont-work-r480/

I'm not saying anything is "wrong" with the existing code, but nuhll found an oversight committed by both of us (ok maybe just me) where dockerupdate.php assumes that if it's called then it should always send out a notification that an update is available.  All I want to do is add in a check before it calls notify to see if update notifications are enabled or not.

**Comment by bergware** [comment]
I don't see DockerUpdate.php calling the notify script, but it is still early morning here and I might overlook.

It would explain the unwanted container update notifications, but haven't reproduced this "bug" myself.

**Comment by Squidly271** [comment]
../scripts/dockerupdate.php

The "bug" is from dockerupdate.php (which CA Autoupdate calls) automatically sending out a notification.  Not a bug in the OS sense, but I need it to not send the notification.  See #482
