### ISSUE TITLE
Feature: Edit docker autostart while array is offline

### ISSUE THREAD

**Issue by OmgImAlexis** [limetech/webgui#502]
Currently there isn't an easy way to update the `autostart` settings of containers before the array starts. Since they come from a file and not the Docker socket we should be able todo this.

**Comment by Squidly271** [comment]
Currently, the file that stores the autostart status of the containers is within the docker.img file, and therefore no way to access or edit it without the array started.

**Comment by OmgImAlexis** [comment]
I'm guessing you're talking about `/var/lib/docker/unraid-autostart`? 😞

**Comment by Squidly271** [comment]
This can now be accomplished if you set up the "image" as a folder instead
