### ISSUE TITLE
UserAdd/UserEdit funny business

### ISSUE THREAD

**Issue by limetech** [limetech/webgui#73]
First we should combine these two somehow to make life simpler, because for one thing, the help text that is present in UserAdd.page is missing from UserEdit.page, such as max length of Description, password, etc.

Re: password - there is max length of 40 specified for this field, but linux and I presume browser login dialog boxes have no such limitation.  A user got into a situation where they set an invalid (to them) password as follows:

The have a very long password string, longer than 40 chars in a file somewhere and they selected/copied to clipboard.  Next they pasted into password field when creating new password for a user.  But webgui is happy to take all chars but only "keeps" the first 40, user does not know that password got truncated.  Later they login via browser login dialog, paste same password, and there is a mismatch.  :(

**Comment by bergware** [comment]
Made an update, see PR.

**Comment by limetech** [comment]
I think it would be better to increase the length of the password field to 128 but limit the width of the field displayed to 40.  Actually we could accept far longer passwords but soon we are going to move to nginx and we'll revisit this topic again at that time.  For now, there is at least one user who wants to use a longer password (though not longer than 128) so let's go ahead and let him.

**Comment by bergware** [comment]
Ok, made it 128 (sure don't want to type such a password)

**Comment by limetech** [comment]
Thanks, me neither, but I might select/copy/paste from a password program such as KeePass.
