### ISSUE TITLE
Formation of certain file names in diagnosics.zip file confuses win10

### ISSUE THREAD

**Issue by limetech** [limetech/webgui#74]
If a file name contains a colon, for example:

smart/SanDisk_Cruzer_Fit_4C530013101116118182-0:0-20161008-1006.txt

Windows will not be able to open this file.  This causes the "right-click/Extract" context menu to fail as well.

The name of these smart files is taken from /dev/disk/by-id.  For some reason, udev appends "-0:0" for usb bus type.  This is the core issue.  Not sure **best** way to solve this yet.

**Comment by bergware** [comment]
The *sed* command is used to format the listing of disk devices. Within this command a simple find and replace can be added, e,g, translate ':' to '-'

**Comment by limetech** [comment]
Sure that would work.

**Comment by bergware** [comment]
PR ready
