### ISSUE TITLE
The Content Security Policy 'block-all-mixed-content' was delivered via a <meta> element outside the document's <head>, which is disallowed. The policy has been ignored.

### ISSUE THREAD

**Issue by OmgImAlexis** [limetech/webgui#760]
https://github.com/limetech/webgui/blob/3ea1bef8753d69f393b17630acab1e4bf3127bb1/plugins/dynamix/CacheDevices.page#L122

This shouldn't be needed as it's already included by the parent page. I'm seeing this in Chrome.

> The Content Security Policy 'block-all-mixed-content' was delivered via a <meta> element outside the document's <head>, which is disallowed. The policy has been ignored.

**Comment by ljm42** [comment]
It seems odd that this div:
  <div id="templatePopupPool" style="display:none">
has <html><head><body> tags as children.

They were added in this commit for Multi-language support:
  https://github.com/limetech/webgui/commit/51159217404616bce75e200d7219b69e8805f0a3

**Comment by bergware** [comment]
Doesn't look relevant anymore.

I don't see any "stray" occurrences of this <meta> element in the current version

**Comment by ljm42** [comment]
Oh you're right, I wasn't looking at the master branch. This can be closed.
