### ISSUE TITLE
New Permissions tool should offer option to operate on user shares

### ISSUE THREAD

**Issue by limetech** [limetech/webgui#78]
The tool was originally created as part of upgrade from unRAID OS version 4.7 and earlier.  Since then the tool has been useful for other purposes where somehow ownership/permissions has been messed up.

This enhancement adds another dropdown that lets user select any of the current user shares.

**Comment by bergware** [comment]
Added user shares as a selection. See PR

**Comment by bergware** [comment]
Anything you like to change in the PR?

**Comment by eschultz** [comment]
Looks good Ronald, sorry for the delay
