### ISSUE TITLE
Button order wrong on new "Proceed?" dialog boxes

### ISSUE THREAD

**Issue by limetech** [limetech/webgui#81]
LOL took me a while to notice wth was wrong, but here it is: the "Cancel" and "Ok" buttons are in the wrong order!  That is, the "Ok" button should be on the left and the "Cancel" button should be on the right in all these confirmation dialogs.

**Comment by bergware** [comment]
Actually never noticed that :)

Updated to SweetAlert2 (fork of SweetAlert) which places the buttons as 'expected'. See PR

**Comment by bergware** [comment]
Bugger

New version SweetAlert2 does work different.

**Comment by bergware** [comment]
I took the original SweetAlert script and simply reversed to position of the buttons. Updated dynamix.js with the new code.

**Comment by eschultz** [comment]
"Ok" button now on left and the "Cancel" button is on the right thanks to Ronald's PR.
