### ISSUE TITLE
Docker and VMs missing from menu bar

### ISSUE THREAD

**Issue by limetech** [limetech/webgui#83]
Used to be if Docker is enabled then 'Docker' showed up on menu bar whether array was started or not, and if user clicked Docker menu item with array Stopped, page would say "Array must be started to view Docker containers" (or some such text).  Current behavior is that if array is Stopped, Docker does not show up at all on menu bar whether it's enabled or not.  This is wrong.

Ditto above paragraph for VMs.

**Comment by bergware** [comment]
Created a PR to correct this

**Comment by eschultz** [comment]
Thanks Ronald!
